otus <- read.table('fig2_TSS_normalised.csv',sep=',', header=T,check=F,row.names=1,comment='')
datm <- melt(cbind(otus, ind = rownames(otus)), id.vars = c('ind'))
g <- ggplot(datm,aes(x = variable, y = value,fill = ind)) +  geom_bar(stat = "identity", width = 0.5) +  coord_flip()
g <- g + ylab('Percentage of Sequences')
g <- g + xlab('')
g <- g + theme_bw()
g <- g + scale_fill_manual(values=c("#ffff00","#a6cee3","#1f78b4","#b2df8a","#33a02c","#fb9a99","#e31a1c","#fdbf6f","#ff7f00","#cab2d6","#6a3d9a"))
g <- g + guides(fill=guide_legend(title=NULL))
flevels <- levels (datm$variable)
flevels <- rev(flevels)
g <- g + scale_x_discrete(limits=flevels)
g <- g + theme(axis.text.x=element_text(angle=0, size=13, vjust=0.5))
g <- g + theme(axis.text.y=element_text(angle=0, size=13, vjust=0.5))
g <- g + theme(axis.title.x = element_text(color="black",size=13, vjust=-0.5))
g <- g + theme(plot.margin = unit(c(1,1,1,0), "cm"))
g <- g + theme(legend.text=element_text(size=13))
tiff(file="fig2_TSS_normalised.tiff",width=2200,height=800,res=200)
g
dev.off()
